/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { StoreCategoryDto } from './models/store-category-dto';
export type { StoreDto } from './models/store-dto';
export type { StoreTagDto } from './models/store-tag-dto';
export type { UpdateStoreCategoriesByStoreDto } from './models/update-store-categories-by-store-dto';
export type { UpdateStoresByStoreCategoryDto } from './models/update-stores-by-store-category-dto';
export type { UpdateStoresByStoreTagDto } from './models/update-stores-by-store-tag-dto';
export type { UpdateStoreTagsByStoreDto } from './models/update-store-tags-by-store-dto';
