/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PaymentOrderRelationParams } from './models/payment-order-relation-params';
export type { UpdateOrdersByPaymentDto } from './models/update-orders-by-payment-dto';
export type { UpdatePaymentsByOrderDto } from './models/update-payments-by-order-dto';
export type { UpdateStoresByUserDto } from './models/update-stores-by-user-dto';
export type { UpdateUsersByStoreDto } from './models/update-users-by-store-dto';
export type { ValueTupleOfGuidAndStoreRole } from './models/value-tuple-of-guid-and-store-role';
export type { ValueTupleOfstringAndStoreRole } from './models/value-tuple-ofstring-and-store-role';
