/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateStoreTagsByStoreDto } from '../../models/update-store-tags-by-store-dto';

export interface ApiStoreTagRelationsUpdateStoreTagsByStorePut$Params {
      body: UpdateStoreTagsByStoreDto
}

export function apiStoreTagRelationsUpdateStoreTagsByStorePut(http: HttpClient, rootUrl: string, params: ApiStoreTagRelationsUpdateStoreTagsByStorePut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiStoreTagRelationsUpdateStoreTagsByStorePut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiStoreTagRelationsUpdateStoreTagsByStorePut.PATH = '/api/StoreTagRelations/update-store-tags-by-store';
