/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiStoreTagRelationsGetStoresByStoreTagIdStoreTagIdGet$Params {
  storeTagId: string;
}

export function apiStoreTagRelationsGetStoresByStoreTagIdStoreTagIdGet(http: HttpClient, rootUrl: string, params: ApiStoreTagRelationsGetStoresByStoreTagIdStoreTagIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiStoreTagRelationsGetStoresByStoreTagIdStoreTagIdGet.PATH, 'get');
  if (params) {
    rb.path('storeTagId', params.storeTagId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiStoreTagRelationsGetStoresByStoreTagIdStoreTagIdGet.PATH = '/api/StoreTagRelations/get-stores-by-store-tag-id/{storeTagId}';
