/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoreDto {
  address?: (string | null);
  createdAt?: string;
  currency?: (string | null);
  description?: (string | null);
  id?: string;
  language?: (string | null);
  name?: string;
  themeColor?: (string | null);
  timeZone?: (string | null);
}
