/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ValueTupleOfstringAndStoreRole } from '../models/value-tuple-ofstring-and-store-role';
export interface UpdateUsersByStoreDto {
  storeId?: string;
  userIdsAndStoreRoles?: Array<ValueTupleOfstringAndStoreRole>;
}
