/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ValueTupleOfGuidAndStoreRole } from '../models/value-tuple-of-guid-and-store-role';
export interface UpdateStoresByUserDto {
  storeIdsAndStoreRoles?: Array<ValueTupleOfGuidAndStoreRole>;
  userId?: string;
}
