/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AssignRoleDto } from './models/assign-role-dto';
export type { ChangePasswordDto } from './models/change-password-dto';
export type { IFormFile } from './models/i-form-file';
export type { LoginRequestDto } from './models/login-request-dto';
export type { PermissionDto } from './models/permission-dto';
export type { RoleDto } from './models/role-dto';
export type { UpdatePermissionsByRoleDto } from './models/update-permissions-by-role-dto';
export type { UpdateRolesByPermissionDto } from './models/update-roles-by-permission-dto';
export type { UpdateRolesByUserDto } from './models/update-roles-by-user-dto';
export type { UpdateUsersByRoleDto } from './models/update-users-by-role-dto';
