/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiUserRolesGetUserIdsByRoleIdRoleIdGet$Params {
  roleId: string;
}

export function apiUserRolesGetUserIdsByRoleIdRoleIdGet(http: HttpClient, rootUrl: string, params: ApiUserRolesGetUserIdsByRoleIdRoleIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiUserRolesGetUserIdsByRoleIdRoleIdGet.PATH, 'get');
  if (params) {
    rb.path('roleId', params.roleId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiUserRolesGetUserIdsByRoleIdRoleIdGet.PATH = '/api/UserRoles/get-user-ids-by-role-id/{roleId}';
