/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateStoresByUserDto } from '../../models/update-stores-by-user-dto';

export interface ApiUserStoreRelationsUpdateStoresByUserPut$Params {
      body: UpdateStoresByUserDto
}

export function apiUserStoreRelationsUpdateStoresByUserPut(http: HttpClient, rootUrl: string, params: ApiUserStoreRelationsUpdateStoresByUserPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiUserStoreRelationsUpdateStoresByUserPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiUserStoreRelationsUpdateStoresByUserPut.PATH = '/api/UserStoreRelations/update-stores-by-user';
