/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateOrdersByPaymentDto } from '../../models/update-orders-by-payment-dto';

export interface ApiPaymentOrderRelationsUpdateOrdersByPaymentPut$Params {
      body: UpdateOrdersByPaymentDto
}

export function apiPaymentOrderRelationsUpdateOrdersByPaymentPut(http: HttpClient, rootUrl: string, params: ApiPaymentOrderRelationsUpdateOrdersByPaymentPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiPaymentOrderRelationsUpdateOrdersByPaymentPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiPaymentOrderRelationsUpdateOrdersByPaymentPut.PATH = '/api/PaymentOrderRelations/update-orders-by-payment';
