/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFormFile } from '../../models/i-form-file';

export interface ApiUsersPut$Params {
      body: {
'Id'?: string;
'Email'?: string;
'Code'?: string;
'FullName'?: string;
'PhoneNumber'?: string;
'AvatarUrl'?: string;
'Roles'?: Array<string>;
'File'?: IFormFile;
}
}

export function apiUsersPut(http: HttpClient, rootUrl: string, params: ApiUsersPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiUsersPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiUsersPut.PATH = '/api/Users';
